name: BuildOnPR

on:
  pull_request:
    branches: 
      - main
# We also want to be able to run this manually from Github
  workflow_dispatch:

jobs:
  lintReusableWF:
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/linter.yml@main
  
      
  buildJava_CoreReusableWf:
    needs: [lintReusableWF]
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/build_java.yml@main
    with:
      packagepath: 'hibernate-orm-panache-quickstart/target/*.jar'
      javaversion: '17'
      mavenpath: 'hibernate-orm-panache-quickstart'
      distribution: 'temurin'
      
