name: BuildOnPR

on:
  push:
    branches: 
      - main
# We also want to be able to run this manually from Github
  workflow_dispatch:

env:
  DBHOST: ${{ vars.DBHOST }}
  DBNAME: ${{ vars.DBNAME }}
  DBUSER: ${{ vars.DBUSER }}
  DBPASS: ${{ secrets.DBPASS }}
  USER_NAME: ${{ vars.USER_NAME }}
  
jobs:
  # lintReusableWF:
  #   permissions:
  #     contents: read
  #     packages: read
  #     statuses: write
  #   uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/linter.yml@main
  
  createDockerImage:
    # needs: [lintReusableWF]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
        with:
          driver: docker

      - name: Create image
        run:  ./mvnw clean package -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: export quarkus_tag=$(docker images | grep quarkus_test_aks | head -n1 | cut -d " " -f1) && \
             docker push ${quarkus_tag}:latest 
