name: InfraDeploy

on:
  #push:
  #  branches:
  #    - main

      
  # We also want to be able to run this manually from Github
  workflow_dispatch:
    inputs:
        rg_name: 
            required: false
            default: "ritiktest-rg"
        location:
            required: false
            default: "East US"
        postgres_db_server_name:
            required: false
            default: "postgrestestritik"

jobs:
  infra:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1.4.3
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Template
      run: |
        # az group create --name ${{ inputs.rg_name }} --location ${{ inputs.location }}
        az postgres flexible-server create --name ${{ inputs.postgres_db_server_name }} --resource-group "1-770a3e3a-playground-sandbox" --location "East US" --admin-user "quarkus_test" --admin-password "Test@123" --sku-name Standard_B1ms --tier Burstable --public-access 0.0.0.0-0.0.0.0
        az postgres flexible-server db create --resource-group ${{ inputs.rg_name }}  --server-name ${{ inputs.postgres_db_server_name }} --database-name quarkus_test
        az aks create --resource-group ${{ inputs.rg_name }} --location ${{ inputs.location }} --name "quarkus" --node-count 1 --generate-ssh-keys --enable-managed-identity